import React, { useState, useEffect } from 'react'
import { supabase } from '../lib/supabase'
import { cn } from '../lib/utils'
import {
    CheckCircle2,
    XCircle,
    Clock,
    TrendingUp,
    ArrowUpRight,
    Filter,
    Loader2
} from 'lucide-react'

export default function AlertHistory() {
    const [history, setHistory] = useState<any[]>([])
    const [loading, setLoading] = useState(true)

    useEffect(() => {
        fetchHistory()

        const channel = supabase
            .channel('alerts-history')
            .on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'alerts' }, () => fetchHistory())
            .subscribe()

        return () => {
            supabase.removeChannel(channel)
        }
    }, [])

    const fetchHistory = async () => {
        try {
            const { data } = await supabase
                .from('alerts')
                .select('*')
                .order('created_at', { ascending: false })

            if (data && data.length > 0) {
                setHistory(data)
            } else {
                setHistory([
                    { symbol: 'BTC', price: 52140, change_percent: 4.2, outcome_status: 'watched', created_at: new Date().toISOString() },
                    { symbol: 'TSLA', price: 182.10, change_percent: -2.1, outcome_status: 'acted', created_at: new Date(Date.now() - 86400000).toISOString() },
                ])
            }
        } catch (err) {
            console.error(err)
        } finally {
            setLoading(false)
        }
    }

    if (loading) {
        return (
            <div className="flex-1 flex items-center justify-center min-h-[400px]">
                <Loader2 className="w-12 h-12 text-blue-500 animate-spin opacity-20" />
            </div>
        )
    }

    const stats = {
        successRate: history.length > 0
            ? Math.round((history.filter(a => a.outcome_status === 'acted').length / history.length) * 100)
            : 0,
        alphaGen: history.length > 0
            ? (history.reduce((acc, curr) => acc + (curr.change_percent || 0), 0) / history.length).toFixed(2)
            : '0.00'
    }

    return (
        <div className="flex flex-col gap-10 page-transition">
            <div className="flex flex-col md:flex-row md:items-end justify-between gap-8">
                <div className="space-y-4">
                    <h1 className="text-5xl font-black tracking-tighter text-slate-950 leading-tight">Intelligence Logs</h1>
                    <p className="text-slate-500 font-medium max-w-xl">Historical record of all institutional signals generated by your autonomous agents.</p>
                </div>

                <div className="flex gap-4">
                    <div className="premium-card bg-white px-8 py-5 flex flex-col items-center shadow-lg border border-white/80">
                        <span className="text-[9px] font-black text-slate-400 uppercase tracking-widest mb-1">Success Rate</span>
                        <span className="text-black font-black text-2xl tracking-tight">{stats.successRate}%</span>
                    </div>
                    <div className="premium-card bg-white px-8 py-5 flex flex-col items-center shadow-lg border border-white/80">
                        <span className="text-[9px] font-black text-slate-400 uppercase tracking-widest mb-1">Alpha Gen</span>
                        <span className="text-emerald-500 font-black text-2xl tracking-tight">+{stats.alphaGen}%</span>
                    </div>
                </div>
            </div>

            {/* Filter Bar */}
            <div className="flex items-center justify-between">
                <div className="flex gap-3 overflow-x-auto pb-1 no-scrollbar">
                    {['All History', 'High Conviction', 'Trends', 'Earnings'].map((f, i) => (
                        <button key={f} className={cn(
                            "px-6 py-3 rounded-xl text-[10px] font-black uppercase tracking-widest transition-all",
                            i === 0 ? "bg-black text-white shadow-xl" : "bg-white/60 text-slate-500 hover:bg-white hover:text-black border border-white/40"
                        )}>{f}</button>
                    ))}
                </div>
                <button className="p-3 bg-white rounded-xl border border-white/40 text-slate-400 hover:text-black transition-all shadow-sm">
                    <Filter size={18} />
                </button>
            </div>

            {/* List of Historical Alerts */}
            <div className="space-y-4">
                {history.map((item, i) => (
                    <div key={item.id || i} className="premium-card bg-white/40 hover:bg-white p-6 flex flex-col md:flex-row items-center justify-between gap-8 group cursor-pointer transition-all border border-transparent hover:border-slate-200">
                        <div className="flex items-center gap-8 flex-1">
                            <div className={cn(
                                "w-16 h-16 rounded-2xl flex items-center justify-center border transition-all duration-500 group-hover:rotate-6 shadow-sm border-white/50",
                                item.change_percent >= 0 ? "bg-emerald-50 text-emerald-600 border-emerald-100" :
                                    "bg-rose-50 text-rose-600 border-rose-100"
                            )}>
                                {item.change_percent >= 0 ? <CheckCircle2 size={24} /> : <XCircle size={24} />}
                            </div>

                            <div className="space-y-1">
                                <div className="flex items-center gap-4">
                                    <span className="text-2xl font-black tracking-tighter text-black">{item.symbol}</span>
                                    <span className="px-3 py-1 bg-slate-900/5 rounded-md text-[9px] font-black text-slate-400 uppercase tracking-widest leading-none">
                                        {item.outcome_status.toUpperCase()}
                                    </span>
                                </div>
                                <div className="text-[11px] text-slate-400 font-bold uppercase tracking-tight flex items-center gap-2">
                                    {new Date(item.created_at).toLocaleDateString()} • ${Number(item.price).toLocaleString()} authenticated entry
                                </div>
                            </div>
                        </div>

                        <div className="flex items-center gap-12 pr-4">
                            <div className="text-right">
                                <div className="text-[9px] font-black text-slate-400 uppercase tracking-widest mb-1.5">Return</div>
                                <div className={cn(
                                    "text-xl font-black font-mono tracking-tighter",
                                    item.change_percent >= 0 ? "text-emerald-500" : "text-rose-500"
                                )}>{item.change_percent >= 0 ? '+' : ''}{item.change_percent}%</div>
                            </div>

                            <div className="p-3 rounded-xl bg-slate-50 text-slate-400 group-hover:bg-slate-900 group-hover:text-white transition-all shadow-sm">
                                <ArrowUpRight size={20} />
                            </div>
                        </div>
                    </div>
                ))}
            </div>

            {/* Accuracy Analytics */}
            <section className="bg-[#0F172A] text-white rounded-[2.5rem] p-12 mt-4 shadow-huge relative overflow-hidden flex flex-col lg:flex-row gap-16 items-center border border-white/5">
                <div className="absolute top-0 right-0 w-[400px] h-[400px] bg-emerald-500/5 blur-[100px]" />
                <div className="space-y-4 max-w-sm">
                    <div className="p-4 bg-white/5 rounded-2xl w-fit shadow-inner border border-white/5"><TrendingUp size={28} className="text-emerald-400" /></div>
                    <h3 className="text-3xl font-black tracking-tighter">Precision Mapping</h3>
                    <p className="text-sm text-slate-400 leading-relaxed font-medium">
                        Metrics adjusted for liquidity drift and execution lag across normalized regimes.
                    </p>
                </div>

                <div className="flex-1 w-full grid grid-cols-1 md:grid-cols-3 gap-10 relative z-10">
                    <MetricBar label="Equity Alpha" value={72} color="emerald" />
                    <MetricBar label="Crypto Vol" value={44} color="blue" />
                    <MetricBar label="Forex Trend" value={61} color="purple" />
                </div>
            </section>
        </div>
    )
}

function MetricBar({ label, value, color }: { label: string, value: number, color: 'emerald' | 'blue' | 'purple' }) {
    const colors = {
        emerald: "bg-emerald-500 shadow-[0_0_15px_rgba(16,185,129,0.3)]",
        blue: "bg-blue-500 shadow-[0_0_15px_rgba(59,130,246,0.3)]",
        purple: "bg-purple-500 shadow-[0_0_15px_rgba(168,85,247,0.3)]"
    }
    return (
        <div className="space-y-4">
            <div className="flex justify-between items-end">
                <span className="text-[9px] font-black uppercase tracking-[0.2em] text-slate-500">{label}</span>
                <span className="text-2xl font-black font-mono">{value}%</span>
            </div>
            <div className="h-1.5 bg-white/5 rounded-full overflow-hidden">
                <div className={cn("h-full rounded-full transition-all duration-1000", colors[color])} style={{ width: `${value}%` }} />
            </div>
        </div>
    )
}
